### ISSUE TITLE
Clarity on how docker compose based devcontainers are built

### ISSUE THREAD

**Issue by amitds1997** [devcontainers/spec#331]
The spec does not provide clarity on how to specify the build context for a Docker compose build. Considering the following project structure

```
| .devcontainer
     | devcontainer.json
| docker-compose.yml
| Dockerfile
| requirements.txt
```
How should I specify the build context? This is a sample repository: https://github.com/amitds1997/devpod-cache-issue.

Reference `devcontainer.json`:
```json
{
  "name": "Debug service",
  "dockerComposeFile": "../docker-compose.yml",
  "service": "main-app",
  "workspaceFolder": "/root",
  "shutdownAction": "stopCompose",
}
```

Should it be specified as:

1. In `.devcontainer.json` file, or

```json
{
 "build": {
    "context": ".."
  },
}
```

2. In `docker-compose.yml` file (to indicate that it is one directory above from `devcontainer.json` file where it is used)

```yaml
version: '3'

services:
  main-app:
    build:
      context: ..
    restart: always
    ports:
    - "5003:5000"
    command: python -m http.server 5000
```

3. Or, should it be assumed to be running from the `docker-compose.yml`'s directory?

**Comment by samruddhikhandale** [comment]
Hi 👋 

> In .devcontainer.json file, or

According to https://containers.dev/implementors/json_reference/#compose-specific, for docker compose containers, we don't allow that property. `build.context` is only helpful for images or dockerfile based containers.

> In docker-compose.yml file (to indicate that it is one directory above from devcontainer.json file where it is used)

The `build.context` in the `docker-compose.yml` file uses the definition from Docker. See https://docs.docker.com/compose/compose-file/build/#context (context defines either a path to a directory containing a Dockerfile, or a URL to a git repository.)

Hence, in your case `build` should be defined as follows 👇 

```
services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
```

Let us know if this makes sense, or if you have any more questions.

Feel free to take a look at https://github.com/devcontainers/templates/tree/main which has more examples (eg. [go-postgres Template](https://github.com/devcontainers/templates/tree/main/src/go-postgres))

Also, you can refer to https://containers.dev/guide/dockerfile which explains the use of Images, Dockerfiles, and Docker Compose.
