### ISSUE TITLE
Docker 25 gives error using network_mode parameter

### ISSUE THREAD

**Issue by SteeveGL** [devcontainers/spec#445]
Devcontainer won't start if you set using docker-compose file and set the parameter `network_mode`. I could reproduce the issue with Docker version 25.0.4 but not with docker version 24.0.9.

I don't have hand on log right now, but they wasn't really helpful. Just complaining about the container not running and also the container was exit with code 0.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Would you be able to provide us with a sample dev container for being able to reproduce this issue? I wasn't able to reproduce the issue.

**Comment by SteeveGL** [comment]
@samruddhikhandale there is

```yaml
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:mongo
    command: sleep infinity

  mongo:
    image: mongo:7.0.4

  mongo-express:
    image: mongo-express
    ports:
      - 8091:8081

```

Since I downgraded to Docekr version 24 and network_mode give me issue with DNS. No name resolution.
